### ISSUE TITLE
Error Executing action with revive version 1.3.5

### ISSUE THREAD

**Issue by danteay** [morphy2k/revive-action#124]
## Description

Since last upgrade to revive 1.3.5 Dockerfile doesn't buld correctly on pipeline causing to fail related actions:

![Screenshot 2024-01-04 at 10 00 02 a m](https://github.com/morphy2k/revive-action/assets/9085902/f8d00b32-6903-4394-837e-e90f1bb6730d)

**Comment by morphy2k** [comment]
See https://github.com/mgechev/revive/issues/956

I hope for a new Revive release shortly.

**Comment by shaunco** [comment]
@morphy2k - https://github.com/mgechev/revive/issues/956 is closed now with revive v1.3.6 available.

**Comment by morphy2k** [comment]
Just published v2.5.6
