### ISSUE TITLE
v2.5.5 build process fails

### ISSUE THREAD

**Issue by morphy2k** [morphy2k/revive-action#125]
Due to an issue with Revive v1.3.5 in connection with `go install`, the build process of v2.5.5 fails.

https://github.com/mgechev/revive/issues/956

**Comment by denisvmedia** [comment]
JFYI: I've just published Revive v1.3.6 with the fix.

**Comment by morphy2k** [comment]
@denisvmedia Thank you!

I just published v2.5.6
