### ISSUE TITLE
v2.5.8 failing with: "go": executable file not found in $PATH

### ISSUE THREAD

**Issue by hnrkndrssn** [morphy2k/revive-action#135]
v2.5.7 build successful https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/runs/10106749988/job/27949407229?pr=690

v2.5.8 build failed https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/runs/10106735748/job/27949369024

**Comment by mikeatlas** [comment]
This is problematic for me since my org has only approved the `v2` tag which presumably is loading 2.5.8. As such I can't simply specify the minor version 2.5.7 without going through some internal hurdles. It'd be great to have this fixed quickly...

**Comment by morphy2k** [comment]
Caused by this https://github.com/mgechev/revive/commit/4242f24f4df2f1d58a7ec639fe9b365cf5a5714c#diff-d11e824011a3a8f692c13fb88e333ea5c84a40b02ed50566d4775e0238c25507R127

Revive now requires Go on the system. Wasn't documented anywhere.

I will fix it with a new release in the next few hours.

**Comment by mikeatlas** [comment]
confirmed - https://github.com/morphy2k/revive-action/pull/136 is working (v2.5.9)

**Comment by morphy2k** [comment]
The dependency on Go has been removed again (https://github.com/mgechev/revive/pull/1025). So we'll be able to undo the changes with the next Revive release. So again, standalone and small Docker image.

**Comment by morphy2k** [comment]
With the just released 2.5.11, everything should be as it was before.
