### ISSUE TITLE
Custom path?

### ISSUE THREAD

**Issue by tedmiston** [morphy2k/revive-action#6]
Is it possible to pass a custom subpath in my repo to the Revive Action?

I run this via the `revive` CLI like so:

```
$ revive ./foo/bar/...
```

I haven't found a way to either pass this path to the Revive Action or as a fallback put it in the config.toml.

**Comment by morphy2k** [comment]
This is actually already on my ToDo list. I will try to implement that in the coming days.

**Comment by tedmiston** [comment]
Right after opening this, I went ahead and forked the repo and added the arg and it was easier than I anticipated.  I need to cleanup one part and squash the commits but I can send a PR back if interested.

**Comment by morphy2k** [comment]
Yeah, sure, if you want :-)
